# Every field in a theme file is optional.

shadow = false
borders = "outset" # Alternatives are "none" and "simple"

# Base colors are red, green, blue,
# cyan, magenta, yellow, white and black.
[colors]
	background = ["#161616"]

	# If the terminal doesn't support custom color (like the linux TTY),
	# non-base colors will be skipped.
	shadow     = ["#111", "blue"]
	view       = "111"

	# An array with a single value has the same effect as a simple value.
	primary   = ["white"]
	secondary = "#EEEEEE"
	tertiary  = "#252521"

	# Hex values can use lower or uppercase.
	# (base color MUST be lowercase)
	title_primary   = ["BLUE", "yellow"] # `BLUE` will be skipped.
	title_secondary = "#ffff55"

	# Lower precision values can use only 3 digits.
	highlight          = "#F88"
	highlight_inactive = "#5555FF"
